### ISSUE TITLE
Run-time Error due to scapy version

### ISSUE THREAD

**Issue by shubham8agar** [llmora/tolerantls#1]
# python tolerantls.py --host example.com
Traceback (most recent call last):
  File "tolerantls.py", line 5, in <module>
    from scapy_ssl_tls.ssl_tls import *
  File "/usr/local/lib/python2.7/dist-packages/scapy_ssl_tls/ssl_tls.py", line 691, in <module>
    class TLSHelloRetryRequest(Packet):
  File "/usr/local/lib/python2.7/dist-packages/scapy_ssl_tls/ssl_tls.py", line 695, in TLSHelloRetryRequest
    TypedPacketListField("extensions", None, TLSExtension, length_from=lambda x:x.length, type_="TLSHelloRetryRequest")]
  File "/usr/local/lib/python2.7/dist-packages/scapy_ssl_tls/ssl_tls.py", line 228, in __init__
    self.type_ = type_
AttributeError: 'TypedPacketListField' object has no attribute 'type_'

**Comment by llmora** [comment]
Thanks for reporting the issue.

It looks like a scapy/scapy_ssl_tls incompatibility issue, but we are unable to reproduce. Can you share the version of scapy/scapy_ssl_tls installed and, ideally, installation logs for both tools?

**Comment by shubham8agar** [comment]
Thanks for your reply. I a, unable to get version of scapy or installation logs. But if I repeat the installation process it shows as follows:

# pip install scapy scapy-ssl_tls
Requirement already satisfied: scapy in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: scapy-ssl_tls in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: tinyec>=0.3.1 in /usr/local/lib/python2.7/dist-packages (from scapy-ssl_tls)
Requirement already satisfied: pycryptodomex>=3.4 in /usr/local/lib/python2.7/dist-packages (from scapy-ssl_tls)

**Comment by shubham8agar** [comment]
I checked and found that scapy version is 
scapy-2.3.3 scapy-ssl-tls-2.0.0

**Comment by llmora** [comment]
Thanks for this, I am able to reproduce the issue with scapy-2.3.3.

I will work on a solution, until then a quick workaround is to downgrade to scapy-2.3.2.

**Comment by llmora** [comment]
From our tests there is a need to have very specific versions of `scapy` installed for `scapy-ssl-tls` to work properly, as the latter patches scapy files during installation, and any version misalignment leads to `scapy` files being mangled.

The solution is installing specific versions of the library, e.g.:

```
pip install 'scapy>=2.2.0,<2.3.3' 'scapy-ssl_tls==1.2.3'
```

Make sure you remove any previously installed versions to avoid conflicts. From our tests this is the more resilient way to ensure appropriate operation of `tolerantls`.

Can you confirm if this resolved the issue for you?

**Comment by shubham8agar** [comment]
Yes, it resolved the issue with **scapy** and **scapy-ssl_tls** . But I found that there is some issue with **python version** too. Opening a separate issue for that. Thanks..
