### ISSUE TITLE
Different Error with Different Python Versions.

### ISSUE THREAD

**Issue by shubham8agar** [llmora/tolerantls#2]
With default python version in my system i.e.  python2.7 following Error output 

**# python2.7 tolerantls.py --host google.com
[*] Testing TLS version intolerance against google.com:443
Traceback (most recent call last):
  File "tolerantls.py", line 43, in <module>
    main()
  File "tolerantls.py", line 25, in main
    p = TLSRecord(version=0x03EE) / TLSHandshakes(handshakes=[TLSHandshake() /
NameError: global name 'TLSHandshakes' is not defined**

With python2.7 following Error output 

**# python3 tolerantls.py --host google.com
  File "tolerantls.py", line 19
    print "[*] Testing TLS version intolerance against %s:%s" % (args.host, args.port)
                                                            ^
SyntaxError: invalid syntax**

**Comment by llmora** [comment]
Fixed the issue with python2.7 in HEAD (it was really an issue with the ssl-tls module downgrade). As for python3 support, neither scapy nor scapy-ssl_tls currently support python3.

Let us know if this resolves the issue please.

**Comment by shubham8agar** [comment]
Yeah.. checked it out and the issue has been fixed. Working fine.
